version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: sunday
      labels:
          - 'dependencies'
      commit-message:
          prefix: 'chore'
          include: 'scope'
      ignore:
          - dependency-name: '*'
            update-types:
                - 'version-update:semver-major'
      groups:
          all-npm:
              patterns:
                  - '*'
