version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      open-pull-requests-limit: 0 # Disable scheduled version updates, only allow security updates
      labels:
          - 'dependencies'
          - 'security'
      assignees:
          - 'dependabot[bot]'
      groups:
          dependencies:
              patterns:
                  - '*'
