name: 'Publish on Merge'

on:
    push:
        branches:
            - trunk

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Setup Node.js
              uses: actions/setup-node@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
    eslint:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
            - name: Lint DIVE
              run: yarn lint
    unit:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
            - name: Unit-Test DIVE
              run: yarn coverage
            - name: Upload coverage to Codecov (set new baseline)
              run: npx codecov -f coverage/coverage-final.json -B
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    prettier-fix:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
            - name: Prettier fix DIVE
              run: yarn prettier:fix && git add .
    publish:
        runs-on: ubuntu-latest
        needs: [eslint, unit, prettier-fix]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            - name: Search for cached dependencies
              uses: actions/cache@v4
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn

            - name: Register git user
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"

            - name: Build DIVE
              run: yarn build

            - name: 'Add tag'
              run: git tag -a $(node -p "require('./package.json').version") -m "DIVE Release Version $(node -p "require('./package.json').version")"

            - name: 'Push tag'
              run: git push origin tag $(node -p "require('./package.json').version")

            - name: Publish DIVE to npm
              uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: 'public'
                  dry-run: false

            - name: 'Automated Version Bump'
              uses: 'phips28/gh-action-bump-version@master'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_USER: 'GitHub Actions'
                  GITHUB_EMAIL: 'actions@github.com'
              with:
                  target-branch: 'trunk'
                  commit-message: 'Automated Version Bump [skip ci]'
                  skip-push: 'true'
                  skip-tag: 'true'
                  version-type: 'patch'

            - name: Push to protected branch trunk
              uses: CasperWA/push-protected@v2
              with:
                  token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
                  branch: trunk
                  unprotect_reviews: true
                  tags: true
                  force: true
