name: 'Publish Beta Manually'

on:
    workflow_dispatch: # This allows manual triggering only from the Actions tab

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Setup Node.js
              uses: actions/setup-node@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
    eslint:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
            - name: Lint DIVE
              run: yarn lint
    unit:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
            - name: Unit-Test DIVE
              run: yarn unit
    prettier-fix:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
            - name: Prettier fix DIVE
              run: yarn prettier:fix && git add .
    publish-beta:
        runs-on: ubuntu-latest
        needs: [eslint, unit, prettier-fix]
        permissions:
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            - name: Search for cached dependencies
              uses: actions/cache@v4
              id: yarn-cache
              with:
                  path: node_modules
                  key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn

            - name: Get short-lived token
              uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
              id: sts
              with:
                  scope: shopware/dive
                  identity: push-trunk # matches push-trunk.sts.yaml
            - name: Register git user
              run: |
                  git config user.name "octo-sts bot"
                  git config user.email "octo-sts@example"
                  git remote set-url origin \
                    https://x-access-token:${{ steps.sts.outputs.token }}@github.com/shopware/dive.git
                  git remote -v

            - name: Calculate next beta version from branches
              id: calculate-beta
              run: |
                  # Fetch all tags
                  git fetch --tags

                  # Get the current version from package.json
                  current_version=$(node -p "require('./package.json').version")

                  # Find all beta tags matching the pattern
                  prefix="$current_version-beta."
                  last_beta=$(git tag --list "${prefix}*" | sed "s/${prefix}//" | sort -n | tail -n 1)

                  if [ -z "$last_beta" ]; then
                    next_beta="$current_version-beta.0"
                  else
                    next_beta="$current_version-beta.$((last_beta + 1))"
                  fi

                  # Export the next beta version
                  echo "next_beta=$next_beta" >> $GITHUB_OUTPUT

            - name: Update package.json with new beta version
              run: |
                  npm version --no-git-tag-version ${{ env.next_beta }}
                  git add package.json

            - name: Build DIVE
              run: yarn build

            - name: 'Add tag'
              run: git tag -a ${{ env.next_beta }} -m "DIVE Beta Version ${{ env.next_beta }}"

            - name: 'Print git remote'
              run: git remote -v
            - name: 'Push tag'
              run: git push origin tag ${{ env.next_beta }}"

            - name: Authenticate with NPM
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

            - name: Publish Beta tag to npm
              run: |
                  yarn publish --tag beta
