name: Beta Release

on:
  workflow_dispatch:  # This allows manual triggering only from the Actions tab

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Setup Node.js
              uses: actions/setup-node@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key:
                      node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
    eslint:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key:
                      node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
            - name: Lint DIVE
              run: yarn lint
    unit:
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout DIVE
              uses: actions/checkout@main
            - name: Search for cached dependencies
              uses: actions/cache@main
              id: yarn-cache
              with:
                  path: node_modules
                  key:
                      node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install DIVE dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn
            - name: Unit-Test DIVE
              run: yarn unit
    prettier-fix:
        runs-on: ubuntu-latest
        needs: install
        steps:
          - name: Checkout DIVE
            uses: actions/checkout@main
          - name: Search for cached dependencies
            uses: actions/cache@main
            id: yarn-cache
            with:
                path: node_modules
                key:
                    node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          - name: Install DIVE dependencies (if cache not found)
            if: steps.yarn-cache.outputs.cache-hit != 'true'
            run: yarn
          - name: Prettier fix DIVE
            run: yarn prettier:fix && git add .
    publish-beta:
        runs-on: ubuntu-latest
        needs: [eslint, unit, prettier-fix]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            - name: Search for cached dependencies
              uses: actions/cache@v4
              id: yarn-cache
              with:
                  path: node_modules
                  key:
                      node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
            - name: Install dependencies (if cache not found)
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn

            - name: Register git user
              run: |
                git config user.name "GitHub Actions"
                git config user.email "actions@github.com"

            - name: Bump version to beta
              run: |
                npm version prerelease --preid=beta --no-git-tag-version
                git add package.json

            - name: Build DIVE
              run: yarn build

            - name: Add build files
              run: git add ./build -f

            - name: 'Create beta branch'
              run:
                  git checkout -b beta/v$(node -p "require('./package.json').version")

            - name: Commit changes
              run: |
                git commit -m "Beta v$(node -p "require('./package.json').version")"
                git tag -a v$(node -p "require('./package.json').version") -m "Beta v$(node -p "require('./package.json').version")"

            - name: Push changes
              run: |
                git push origin beta/v$(node -p "require('./package.json').version") --follow-tags

            - name: Authenticate with NPM
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

            - name: Publish Beta tag to npm
              run: |
                yarn publish --tag beta
